FROM nginx:1.17.3-alpine

COPY src/* /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf

#Puerto que le dimos al nginx en el archivo default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]